name: Test action
description: This is just a test action.

inputs:
  greeting:
    description: A greeting
    default: Hello!

outputs:
  greet-back:
    description: An answer

runs:
  using: node20
  main: index.ts
