name: CI - Build the actions

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
      # Triggers the workflow when labels change in the PR
      - labeled

jobs:
  build:
    uses: cmaster11/gha/.github/workflows/build.yml@main
    permissions:
      pull-requests: write
      contents: write
      actions: write
      statuses: write