name: Test action-test
on:
  workflow_dispatch: { inputs: { ctx: {} } }
  # Register the workflow so that it can be triggered
  # via workflow_dispatch event
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-action-test.yml

jobs:
  test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ fromJSON(inputs.ctx).ref }}'

      - id: action
        uses: ./
        with:
          greeting: Hello world!

      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action) }}

  ci-after-test:
    needs:
      - test
    if: always() && github.event_name == 'workflow_dispatch'
    uses: cmaster11/gha/.github/workflows/ci-post-build-after-test.yml@main
    permissions:
      statuses: write
    with:
      ctx: ${{ inputs.ctx }}
      needs-json: ${{ toJSON(needs) }}
